import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { PostsProvider } from "@/context/PostsContext";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={dmSans.variable}>
        <PostsProvider>
          <div className="max-w-[1920px] mx-auto">{children}</div>
        </PostsProvider>
      </body>
    </html>
  );
}
